### ISSUE TITLE
Missing /usr/lib/chromium/swiftshader/libGLESv2.so

### ISSUE THREAD

**Issue by kaijk** [grafana/grafana-image-renderer#156]
**What happened**:
Remote Renderer fails with missing library. Process then times out.
Unnamed Font also missing (Related?)

**What you expected to happen**:
PNG to be created

**How to reproduce it (as minimally and precisely as possible)**:
Create new panel with one series, all defaults otherwise.
Select: Share > Direct link rendered image
New browser window opens empty and loading until the 60s timeout occurs at which point Grafana window reports "Rendering Failed". 

**Anything else we need to know?**:
Grafana and Remote renderer are on same subnet.

A "find" for the missing library in the docker container comes up empty

Note that `# ldd /usr/lib/chromium/chrome` does not show the missing library as a `chrome` dependency.

Log file attached
[log.txt](https://github.com/grafana/grafana-image-renderer/files/4774950/log.txt)

**Environment**:
- Grafana Image Renderer version: 
latest & 1.0.12
- Grafana version: 
7.0.3
- Installed plugin or remote renderer service: 
Remote Renderer service
- OS Grafana Image Renderer is installed on: 
Docker on Win-10
- User OS & Browser:
Grafana in docker on Raspbian Buster Lite - RsPi 3+B
Browser: Firefox on WIn-10
- Others:

Renderer docker-compose:
```
version: '2'
services:
  renderer:
    container_name: renderer
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: 'true'
      RENDERING_VERBOSE_LOGGING: 'true'
      RENDERING_DUMPIO: 'true'
      LOG_LEVEL: 'debug'
```
Grafana docker compose:
```
Version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /srv/grafana:/var/lib/grafana
    restart:
      unless-stopped
    user: '1000:1000'
    environment:
        GF_AUTH_BASIC_ENABLED:       'false'
        GF_AUTH_ANONYMOUS_ENABLED:   'true'
        GF_AUTH_ANONYMOUS_ORG_NAME:  '<myOrgName>'
        GF_AUTH_ANONYMOUS_ORG_ROLE:  'Admin'
        GF_USERS_ALLOW_SIGN_UP:      'false'
        GF_SECURITY_COOKIE_SAMESITE: 'none'
        GF_RENDERING_SERVER_URL:     http://192.168.2.11:8081/render
        GF_RENDERING_CALLBACK_URL:   http://192.168.2.146:3000/
        GF_LOG_FILTERS:              'rendering:debug'
```
