### ISSUE TITLE
the image is not shown

### ISSUE THREAD

**Issue by ortiga88** [grafana/grafana-image-renderer#166]
I have a docker-compose:

```
 renderer:
    image: grafana/grafana-image-renderer:2.0.0
    container_name: renderer_new
    restart: unless-stopped
    environment:
      - BROWSER_TZ=Europe/Madrid
      - RENDERING_MODE=default
    user: "0"
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    environment:
      ENABLE_METRICS: "true"
    networks:
      - grafana

```

in grafana:

```
 - GF_RENDERING_SERVER_URL=http://renderer:8..../render
 - GF_RENDERING_CALLBACK_URL=http://grafana:4...../
 - GF_LOG_FILTERS=rendering:debug

```

error:

```

{"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana:4.../d-solo/qk2Pk8WMk/jaeger?orgId=1&panelId=10&render=1","level":"error","message":"Browser console error"}
{"url":"/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=cqJWcR684PsNY1tI5OI6NLCEUu7dn4sX&timeout=2&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2Fqk2Pk8WMk%2Fjaeger%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000","stack":"TimeoutError: waiting for function failed: timeout 2000ms exceeded\n    at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:549:28)\n    at DOMWorld.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:454:12)\n    at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:657:28)\n    at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/Page.js:1144:29)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:174:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
```
