### ISSUE TITLE
Docker Compose example is not working or incomplete

### ISSUE THREAD

**Issue by oholimoli** [grafana/grafana-image-renderer#207]
**What happened**:

The example is not working:
https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#docker-compose-example

The image renderer is not installed:
![image-renderer](https://user-images.githubusercontent.com/47213738/107362705-66cb9e80-6ad9-11eb-82bc-6057c58efcf9.PNG)

**What you expected to happen**:
Open a dashboard and share a rendered image

**How to reproduce it (as minimally and precisely as possible)**:

Try this example
```
version: '2'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
```

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.4.0
- Installed plugin or remote renderer service: Remote renderer service
- OS Grafana Image Renderer is installed on: Docker
