### ISSUE TITLE
Error loading shared library /usr/lib/chromium/swiftshader/libGLESv2.so

### ISSUE THREAD

**Issue by anuj9196** [grafana/grafana-image-renderer#251]
**What happened**:
Setup renderer as in the demo

```
version: '3.7'

services:
  grafana:
    image: grafana/grafana:8.0.1
    container_name: grafana
    volumes:
    - grafana_storage:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-synthetic-monitoring-app,grafana-worldmap-panel'
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    restart: always

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
      RENDERING_DUMPIO: 'true'

volumes:
  caddy_data:
```

While building the docker container, it produces the error
```
renderer    | {"collectDefaultMetrics":true,"requestDurationBuckets":"1,5,7,9,11,13,15,20,30","level":"info","message":"Metrics enabled"}
renderer    | {"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
renderer    | [0613/014350.956606:WARNING:dns_config_service_linux.cc(464)] Failed to read DnsConfig.
renderer    | [0613/014350.961985:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
renderer    | [0613/014350.968960:ERROR:gl_implementation.cc(394)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: Error loading shared library /usr/lib/chromium/swiftshader/libGLESv2.so: No such file or directory
renderer    |
renderer    | DevTools listening on ws://127.0.0.1:39205/devtools/browser/b650696c-18f0-4643-83d6-ee59999ab52b
renderer    | [0613/014351.000009:ERROR:viz_main_impl.cc(160)] Exiting GPU process due to errors during initialization
renderer    | [0613/014351.023270:ERROR:gl_implementation.cc(394)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: Error loading shared library /usr/lib/chromium/swiftshader/libGLESv2.so: No such file or directory
renderer    | [0613/014351.038184:ERROR:viz_main_impl.cc(160)] Exiting GPU process due to errors during initialization
renderer    | [0613/014351.054860:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for disabled
renderer    | [0613/014351.054981:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
```

**What you expected to happen**:
The container should be built and image should be created

**How to reproduce it (as minimally and precisely as possible)**:
Use the above docker-compose configuration to build and run the container

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: latest (3.0.1)
- Grafana version: latest (8.0.1
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on: Ubuntu (docker)
- User OS & Browser: MacOS (Chrome)
- Others:
