### ISSUE TITLE
Image Renderer Timeout with Report PDFs

### ISSUE THREAD

**Issue by jkupidura14** [grafana/grafana-image-renderer#253]
**What happened**: Using a separate pod for remote image renderer, it is timing out when rendering PDFs under the reports feature. This remote image renderer will work with the direct link for dashboards. This issue seems to be caused by the short timeout when rendering the PDF (10s) in comparison to the timeout using when rendering the image through the direct link (60s).

**What you expected to happen**: Renderer the image for the PDF.

**How to reproduce it (as minimally and precisely as possible)**: In the UI, go to reports - new report - select dashboard from list - Preview PDF or Send test Email. Issue occurs when preforming scheduled reports as well but just sends out a blank PDF.

**Anything else we need to know?**: Error of timeout when rendering a PDF from the reports feature:
```
{"url":"/render?deviceScaleFactor=2.000000&domain=grafana.company.net&encoding=&height=412&renderKey=X1NbKGUc1ikeDjSjXpGf7I5bTcvs2fkj&timeout=10&timezone=&url=https%3A%2F%2Fgrafana.company.net%3A443%2Fd-solo%2FqvfL6dXMz%2Ftest-datasource%3FpanelId%3D4%26theme%3Dlight%26render%3D1&width=1070","stack":"TimeoutError: Navigation timeout of 10000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:94:19)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:485:53)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:95:27)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:182:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","level":"error","message":"Request failed"}
```

**Environment**:
- Grafana Image Renderer version: latest
- Grafana version: 7.5.5
- Installed plugin or remote renderer service: Remote renderer service
- OS Grafana Image Renderer is installed on: Based on helm deployment for remote image renderer
- User OS & Browser: Default image renderer browser from helm deployment
- Others: Kubernetes deployment using the latest helm chart. This is our current helm values for the remote image renderer:
```
imageRenderer:
  enabled: true
  replicas: 1
  image:
    repository: grafana/grafana-image-renderer
    tag: latest
    sha: ""
    pullPolicy: Always
  env:
    HTTP_HOST: "0.0.0.0"
    IGNORE_HTTPS_ERRORS: true
    LOG_LEVEL: debug
  serviceAccountName: ""
  securityContext: {}
  hostAliases: []
  priorityClassName: ''
  service:
    enabled: true
    portName: 'http'
    port: 8081
    targetPort: 8081
  grafanaSubPath: ""
  podPortName: http
  revisionHistoryLimit: 10
  networkPolicy:
    # Enable a NetworkPolicy to limit inbound traffic to only the created grafana pods
    limitIngress: false
    # Enable a NetworkPolicy to limit outbound traffic to only the created grafana pods
    limitEgress: false
  resources: 
     limits:
         cpu: 2Gi
         memory: 16Gi
     requests:
         cpu: 2Gi
         memory: 16G
```
