### ISSUE TITLE
Remote Rendering Using Docker - "Failed to get browser version"

### ISSUE THREAD

**Issue by mf42** [grafana/grafana-image-renderer#258]
**What happened**:

Rendering fails.

I installed docker container Grafana and Grafana -Renderer by using the following docker-compose.yaml

```
version: '2'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    container_name: grafana
    environment:
      TZ: Europe/Berlin
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - renderer
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: 'true'
volumes:
  grafana-storage:
```
the two containers started fine and listen both on their ports
Grafana:
```
t=2021-06-30T11:31:27+0200 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url=http://renderer:8081/render/version

t=2021-06-30T11:31:27+0200 lvl=info msg="Backend rendering via external http server" logger=rendering renderer=http version=3.0.1

t=2021-06-30T11:59:38+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=172.21.0.1 time_ms=0 size=0 referer=

```

BUT Renderer starts with:
```
{"collectDefaultMetrics":true,"requestDurationBuckets":"1,5,7,9,11,13,15,20,30","level":"info","message":"Metrics enabled"}

{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}

{"level":"error","message":"Failed to get browser version"}

```

Failed to get browser version???
Chromium seems to be installed fine....

```
/usr/bin # chromium-browser --version
Chromium 91.0.4472.77 
```

**What you expected to happen**:
 - no error message on startup
 - rendering

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: latest
- Grafana version: 8.0.3
- Installed plugin or remote renderer service: - 
- OS Grafana Image Renderer is installed on: Docker
- User OS & Browser: MacOS BigSur &Safari
- Others:

**Comment by joanlopez** [comment]
Hey @mf42,

Looks like the problem is that the `renderer` is listening only for `localhost` requests (see the log line you attached), so it's not responding requests coming from Grafana container. Look at [Remote Rendering Using Docker](https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md) to see how to override that configuration and make `renderer` application listen for application coming from outside the container.

Thanks,
Joan

**Comment by AgnesToulet** [comment]
Hi @mf42,
I was unable to reproduce the issue with your docker-compose file and the Grafana and image renderer versions you used. Is it happening all the time ? Could you add the `RENDERING_DUMPIO` and `LOG_LEVEL` env variables to your docker-compose file as below to enable more logging?
```yaml
  renderer:
    image: grafana/grafana-image-renderer:3.0.1
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: 'true'
      RENDERING_DUMPIO: 'true'
      LOG_LEVEL: debug
```
