### ISSUE TITLE
Last docker image running on k8s pod

### ISSUE THREAD

**Issue by drex333** [grafana/grafana-image-renderer#300]
Good morning, we have some errors happening related with alpine chromium in a pod running the last (3.2.1) docker image released.

This is the log:

`{"level":"info","maxConcurrency":5,"message":"using clustered browser","mode":"context"}                                                                                                                        
{"config":{"acceptLanguage":null,"args":["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--disable-accelerated-2d-canvas","--disable-gpu"],"chromeBin":"/usr/bin/chromium-browser","cluste 
ring":{"maxConcurrency":5,"mode":"context"},"deviceScaleFactor":1,"dumpio":true,"height":500,"ignoresHttpsErrors":true,"maxDeviceScaleFactor":4,"maxHeight":3000,"maxWidth":3080,"mode":"clustered","timingMetr 
ics":false,"verboseLogging":true,"width":1000},"level":"debug","message":"Browser initialized"}                                                                                                                 
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}                                                                                                                            
{"level":"debug","message":"Render request received","url":"http://grafana:80/d-solo/s_ssdLF7z/_?from=now-24h&height=320&panelId=21&theme=light&to=now&var-environment=ocp-dev&var-namespace=confluent&var-pod_ 
name=All&width=960&render=1"}     
                                                                                                                                                                              
[1109/093747.257438:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 71: Permission denied (13)       
                                                                     
[1109/093755.860021:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory       
                                              
[1109/093755.860553:WARNING:dns_config_service_linux.cc(470)] Failed to read DnsConfig.                                                                                                                         
DevTools listening on ws://127.0.0.1:43083/devtools/browser/554f9110-86b5-453d-8900-21e9e9b67320     
                                                                                                           
[1109/093756.057947:ERROR:gl_implementation.cc(403)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: Error loading shared library /usr/lib/chromium/swiftshader/libGLESv2.so: No such file or direct 
ory                                                                
                                                                                                                                            
[1109/093756.258384:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization         
                                                                                               
[1109/093756.958666:WARNING:vaapi_wrapper.cc(589)] VAAPI video acceleration not available for disabled      
                                                                                                   
[1109/093757.057012:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled`

What should be happening?

Thank you in advance.

**Comment by hjpotter92** [comment]
Facing the same issue. The following is the pod spec:
```yaml
  - env:
    - name: ENABLE_METRICS
      value: "true"
    - name: LOG_LEVEL
      value: debug
    - name: RENDERING_ARGS
      value: --no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x758
    - name: RENDERING_DUMPIO
      value: "true"
    - name: RENDERING_VERBOSE_LOGGING
      value: "true"
    image: grafana/grafana-image-renderer:3.6.2
    imagePullPolicy: IfNotPresent
    name: grafana-image-renderer
    ports:
    - containerPort: 8081
      name: image-renderer
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
```

there are 2 containers on the pod; grafana is configured with following:
```yaml
    env:
    - name: GF_AUTH_ANONYMOUS_ENABLED
      value: "true"
    - name: GF_AUTH_ANONYMOUS_ORG_NAME
      value: Main Org
    - name: GF_AUTH_ANONYMOUS_ORG_ROLE
      value: Viewer
    <REDACTED>
    - name: GF_FEATURE_TOGGLES_ENABLE
      value: dashboardPreviews
    - name: GF_LOG_FILTERS
      value: rendering:debug
    - name: GF_RENDERING_CALLBACK_URL
      value: http://localhost:3000/grafana/
    - name: GF_RENDERING_SERVER_URL
      value: http://localhost:8081/render
    - name: GF_SERVER_SERVE_FROM_SUB_PATH
      value: "true"
    - name: GF_UNIFIED_ALERTING_ENABLED
      value: "true"
    - name: GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE
      value: "true"
```

setting `GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE` works fine; but when trying to setup `GF_FEATURE_TOGGLES_ENABLE` to `dashboardPreviews`; the debug logs of `grafana-image-renderer` is full of permission denied and similar errors (small excerpt from logs):

```
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://localhost:3000/grafana/api/annotations?from=1669358942146&to=1669362542146&limit=100&matchAny=false&dashboardUID=dbme6io7k"}
{"level":"error","message":"Browser console error","msg":"Failed to load resource: the server responded with a status of 400 (Bad Request)","url":"http://localhost:3000/grafana/api/ds/query"}
{"level":"debug","message":"Browser request finished","method":"POST","url":"http://localhost:3000/grafana/api/ds/query"}
{"level":"debug","message":"Waiting for dashboard/panel to load","timeout":"10s"}
{"level":"debug","message":"::ffff:127.0.0.1 - - [25/Nov/2022:07:49:10 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=M5Z8F22nO0sXCZvjgQS3nGOko6NYEGPP&timeout=10&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fgrafana%2Fd-solo%2Fdbme6io7k%2Floki-alerts%3ForgId%3D1%26panelId%3D14%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/9.2.6\"\n"}
{"level":"debug","message":"Connection closed","url":"http://localhost:3000/grafana/d-solo/dbme6io7k/loki-alerts?orgId=1&panelId=14&render=1"}
{"level":"debug","message":"Browser request","method":"POST","url":"http://localhost:3000/grafana/api/frontend-metrics"}
{"level":"debug","message":"Browser request finished","method":"POST","url":"http://localhost:3000/grafana/api/frontend-metrics"}
{"err":"TimeoutError: waiting for function failed: timeout 10000ms exceeded\n    at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:445:34)\n    at IsolatedWorld.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:349:26)\n    at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:479:59)\n    at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2446:33)\n    at /usr/src/app/build/browser/browser.js:284:29\n    at Browser.withTimingMetrics (/usr/src/app/build/browser/browser.js:411:20)\n    at Browser.takeScreenshot (/usr/src/app/build/browser/browser.js:280:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Browser.render (/usr/src/app/build/browser/browser.js:230:20)","level":"error","message":"Error while waiting for the panels to load","url":"http://localhost:3000/grafana/d-solo/dbme6io7k/loki-alerts?orgId=1&panelId=14&render=1"}
{"filePath":"/tmp/034ecd01.png","level":"debug","message":"Taking screenshot"}
{"level":"error","message":"Request failed","stack":"Error: Request aborted\n    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1052:15)\n    at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1094:9)\n    at processImmediate (node:internal/timers:466:21)","url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=M5Z8F22nO0sXCZvjgQS3nGOko6NYEGPP&timeout=10&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fgrafana%2Fd-solo%2Fdbme6io7k%2Floki-alerts%3ForgId%3D1%26panelId%3D14%26render%3D1&width=1000"}
{"level":"debug","message":"::ffff:127.0.0.1 - - [25/Nov/2022:07:49:48 +0000] \"GET /render/version HTTP/1.1\" 200 19 \"-\" \"Grafana/9.2.6\"\n"}
{"level":"debug","message":"Render request received","url":"http://localhost:3000/grafana/d-solo/dbme6io7k/loki-alerts?orgId=1&panelId=14&render=1"}
[1125/075004.132031:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1125/075004.132096:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1125/075004.132487:WARNING:dns_config_service_linux.cc(430)] Failed to read DnsConfig.
[1125/075004.135022:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 2054: Permission denied (13)

DevTools listening on ws://127.0.0.1:45001/devtools/browser/de64e10c-9384-4ee9-af9f-843be1a1e77e
[1125/075004.135618:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1125/075004.142282:ERROR:angle_platform_impl.cc(43)] RendererVk.cpp:144 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface
ERR: RendererVk.cpp:144 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface
[1125/075004.161993:ERROR:angle_platform_impl.cc(43)] RendererVk.cpp:144 (VerifyExtensionsPresent): Extension not supported: VK_KHR_xcb_surface
ERR: RendererVk.cpp:144 (VerifyExtensionsPresent): Extension not supported: VK_KHR_xcb_surface
[1125/075004.162128:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1562.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1562.
[1125/075004.162617:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1562.
[1125/075004.162679:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[1125/075004.162735:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[1125/075004.163242:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 2060: Permission denied (13)
[1125/075004.164805:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1125/075004.165035:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 2069: Permission denied (13)
[1125/075004.169747:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 2080: Permission denied (13)
[1125/075004.170774:ERROR:gpu_init.cc(537)] Passthrough is not supported, GL is disabled, ANGLE is 
{"deviceScaleFactor":1,"height":"500","level":"debug","message":"Setting viewport for page","width":"1000"}
{"domain":"localhost","level":"debug","message":"Setting cookie for page","renderKey":"QqrKgBK5oUxZT3RCRDiK0Bix7setxrfe"}
{"level":"debug","message":"Moving mouse on page","x":1000,"y":500}
{"level":"debug","message":"Navigating and waiting for all network requests to finish","url":"http://localhost:3000/grafana/d-solo/dbme6io7k/loki-alerts?orgId=1&panelId=14&render=1"}
```

It appears that [grafana has changed to using root as default group](https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#user-id-changes), instead of using a group called `grafana`; which hasn't reflected in the docker image yet.
