### ISSUE TITLE
After Grafana upgrade to 9, the plugin no longer renders images

### ISSUE THREAD

**Issue by exander77** [grafana/grafana-image-renderer#350]
Part of docker compose file:
```
services:
  main:
    image: grafana/grafana:latest
    environment:
      - 'GF_RENDERING_SERVER_URL=http://renderer:8081/render'
      - 'GF_RENDERING_CALLBACK_URL=http://main:3000/' # tried to add this
  ...
  renderer:
    image: grafana/grafana-image-renderer
```
Already stopped once like a week ago to restore itself with a following update. How to fix this and prevent outages in the future?
