### ISSUE TITLE
Version 3.7.1 alpine docker does not work, timeout and failed to connect to socket errors

### ISSUE THREAD

**Issue by astrolemonade** [grafana/grafana-image-renderer#430]
**What happened**:
Try to use `grafana/grafana-image-renderer:3.7.1` in a docker-compose environment.
**What you expected to happen**:
I expect that it would work without problems.

**How to reproduce it (as minimally and precisely as possible)**:
```yml
version: "3.9"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    depends_on:
      - renderer
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE=true
  renderer:
    image: grafana/grafana-image-renderer:3.7.1
    ports:
      - '8081:8081'
    environment:
      - RENDERING_DUMPIO=true
      - RENDERING_VERBOSE_LOGGING=true
      - LOG_LEVEL=debug
volumes:
  grafana:
```
**Anything else we need to know?**:
Errors:
```
[0526/105747.678689:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
```
```
{"level":"error","message":"Request failed","stack":"TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1036745 is guaranteed to work.\n    at Timeout.onTimeout (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:301:20)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)","url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=mfsUoGvUGD8HrbNv9gzouFDaj0Z3Gs2S&timeout=10&timezone=&url=http%3A%2F%2Flocalhost%3A9121%2Fd-solo%2Fae692790-982d-4960-b389-898c3049bb8c%2Fistio%3Ffrom%3Dnow-1h%26orgId%3D1%26panelId%3D1%26to%3Dnow%26render%3D1&width=1000"}
```
**Environment**:
- Grafana Image Renderer version: 3.7.1
- Grafana version: 9.5.2
- Installed plugin or remote renderer service: none
- OS Grafana Image Renderer is installed on: the one that is in Docker, alpine
- User OS & Browser: Ubuntu 22.04, Firefox 113.0.2(64-bit)
- Others:
