### ISSUE TITLE
Cannot GET /d-solo/....

### ISSUE THREAD

**Issue by OJthe123** [grafana/grafana-image-renderer#537]
Hi.

I tried the renderer docker container with grafana 11.1.0 docker image.
But when I try to render an image with

`http://10.xxx.1.xxx:8081/d-solo/edn2390pup6o0c/tp?orgId=1&from=1716885345846&to=1716885811742&panelId=1`

I get the error in browser:

`Cannot GET /d-solo/edn2390pup6o0c/tp`

and in docker logs
`{"level":"error","message":"::ffff:10.xxx.1.xxx - - [24/Jun/2024:05:55:04 +0000] \"GET /d-solo/edn2390pup6o0c/tp?orgId=1&from=1716885345846&to=1716885811742&panelId=1 HTTP/1.1\" 404 163 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0\"\n"}`

What am I doing wrong?

here are the parts in my docker compose

 ```
grafana:
    image: grafana/grafana-enterprise:main
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - type: bind
        source: ./grafana-provisioning/
        target: /etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_USERNAME
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_PASSWORD
      - GF_SECURITY_ALLOW_EMBEDDING=$GRAFANA_ALLOW_EMBEDDING
      - GF_AUTH_ANONYMOUS_ENABLED=$GRAFANA_AUTH_ANONYMOUS_ENABLED
      - GF_AUTH_ANONYMOUS_ORG_NAME=$GRAFANA_AUTH_ANONYMOUS_ORG_NAME
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000
      - GF_LOG_FILTERS=rendering:debug
      - GF_RENDERING_RENDERER_TOKEN=$GRAFANA_RENDERER_TOKEN
    networks:
        - default

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081
    environment:
      - AUTH_TOKEN=$GRAFANA_RENDERER_TOKEN
    networks:
      - default


```
