### ISSUE TITLE
Alert on slack doesn't contains image but Telegram does

### ISSUE THREAD

**Issue by iamatulsingh** [grafana/grafana-image-renderer#558]
**What happened**: I tried an Alert which is sending image also in alert on Telegram but when using Slack, it's not sending image in the alert

**What you expected to happen**: Slack alert must also contains image of the alert

**How to reproduce it (as minimally and precisely as possible)**: use slack as notification channel with bot token (starts with xoxb-) and not webhook

**Anything else we need to know?**: No

**Environment**:
- Grafana Image Renderer version: 3.11.3
- Grafana version: 11.1.4
- Installed plugin or remote renderer service: remote renderer service
- OS Grafana Image Renderer is installed on: Docker
- User OS & Browser: Windows 11 and chrome
- Others: please find my docker compose I used
```yaml
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./defaults.ini:/usr/share/grafana/conf/defaults.ini
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_UNIFIED_ALERTING_ENABLED: "true"
      GF_UNIFIED_ALERTING_SCREENSHOTS_ENABLED: "true"
      GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: "true"
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
      TZ: Europe/Berlin
  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      TZ: Europe/Berlin
    ports:
      - 8081
```
