### ISSUE TITLE
Grafana image renderer timing out after a Grafana upgrade

### ISSUE THREAD

**Issue by WyrickC** [grafana/grafana-image-renderer#637]
**What happened**:

We recently upgraded our Grafana to v11.5.3 and now our image renderer (on v3.11.1)  is timing out when trying to access the grafana API. They both run in k8s within the same pod. Alerts using this feature no longer upload images with them. It logs errors like these constantly:

```
{"err":"TimeoutError: Navigation timeout of 10000 ms exceeded\n at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:27:33)\n at listOnTimeout (node:internal/timers:569:17)\n at process.processTimers (node:internal/timers:512:7)","level":"error","message":"Error while trying to prepare page for screenshot","url":"http://localhost:3001/d-solo/ww5xMd-Sz/cluster-node-and-pod-health?orgId=1&panelId=1454&render=1"}
{"err":"TimeoutError: Navigation timeout of 10000 ms exceeded\n at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:27:33)\n at listOnTimeout (node:internal/timers:569:17)\n at process.processTimers (node:internal/timers:512:7)","level":"error","message":"Error while trying to prepare page for screenshot","url":"http://localhost:3001/d-solo/Wyf8STx7z/pgbackrest-exporter-dashboard?orgId=1&panelId=30&render=1"}
{"err":"TimeoutError: Navigation timeout of 10000 ms exceeded\n at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:27:33)\n at listOnTimeout (node:internal/timers:569:17)\n at process.processTimers (node:internal/timers:512:7)","level":"error","message":"Error while trying to prepare page for screenshot","url":"http://localhost:3001/d-solo/Wyf8STx7z/pgbackrest-exporter-dashboard?orgId=1&panelId=32&render=1"}
{"level":"error","message":"Request failed","stack":"Error: Request aborted\n at onaborted (/usr/src/app/node_modules/express/lib/response.js:1061:15)\n at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1103:9)\n at process.processImmediate (node:internal/timers:476:21)","url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=png&height=500&renderKey=gtQ6fVUxcAOl5qRgLAVfjk3mIAw98qfm&timeout=10&timezone=&url=http%3A%2F%2Flocalhost%3A3001%2Fd-solo%2Fww5xMd-Sz%2Fcluster-node-and-pod-health%3ForgId%3D1%26panelId%3D1454%26render%3D1&width=1000"}
{"level":"error","message":"Request failed","stack":"Error: Request aborted\n at onaborted (/usr/src/app/node_modules/express/lib/response.js:1061:15)\n at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1103:9)\n at process.processImmediate (node:internal/timers:476:21)","url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=png&height=500&renderKey=iI5Uf4lIGy7FHNrmZFkGTqg1aU1LWiRj&timeout=10&timezone=&url=http%3A%2F%2Flocalhost%3A3001%2Fd-solo%2FWyf8STx7z%2Fpgbackrest-exporter-dashboard%3ForgId%3D1%26panelId%3D30%26render%3D1&width=1000"}
{"level":"error","message":"Request failed","stack":"Error: Request aborted\n at onaborted (/usr/src/app/node_modules/express/lib/response.js:1061:15)\n at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1103:9)\n at process.processImmediate (node:internal/timers:476:21)","url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=png&height=500&renderKey=hRng9uVnehIHgetISS9SPUxbcDb5kdt2&timeout=10&timezone=&url=http%3A%2F%2Flocalhost%3A3001%2Fd-solo%2FWyf8STx7z%2Fpgbackrest-exporter-dashboard%3ForgId%3D1%26panelId%3D32%26render%3D1&width=1000"}
```

**What you expected to happen**:

I expect the renderer to not timeout to the callback URL and to upload images with alerts successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Run grafana v11.5.3 and the image renderer within the same k8s deployment as such:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - args:
            - '-config=/etc/grafana/grafana.ini'
          env:
            - name: GF_INSTALL_PLUGINS
              value: >-
                grafana-clock-panel, volkovlabs-variable-panel,
                https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app,
                yesoreyeram-infinity-datasource
            - name: GF_RENDERING_SERVER_URL
              value: http://localhost:8081/render
            - name: GF_RENDERING_CALLBACK_URL
              value: http://localhost:3001/
            - name: GF_LOG_FILTERS
              value: rendering:debug
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: docker-proxy/grafana/grafana:11.5.3
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
            - containerPort: 9094
              name: gossip-tcp
              protocol: TCP
            - containerPort: 9094
              name: gossip-udp
              protocol: UDP
        - image: >-
            docker-proxy/grafana/grafana-image-renderer:3.11.1
          imagePullPolicy: IfNotPresent
          name: grafana-image-renderer
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
      serviceAccountName: grafana
      volumes:
        - name: grafana-config
          secret:
            defaultMode: 420
            secretName: grafana-config
        - emptyDir: {}
          name: grafana-image-storage
```

And with this config (replaced sensitive vars):

```
[paths]
data = /var/lib/grafana
logs = /var/lib/grafana/logs
plugins = /var/lib/grafana/plugins
#provisioning = /etc/grafana/provisioning

[server]
http_addr = 
http_port = 3001
root_url = <grafana-address>

[auth.anonymous]
# enable anonymous access
enabled = true
# specify organization name that should be used for unauthenticated users
org_name = Main Org.
# specify role for unauthenticated users
org_role = Viewer

[auth.ldap]
enabled = true
allow_sign_up = true
config_file = /etc/grafana/ldap/ldap.toml

[live]
allowed_origins = "https://*.my-company"

[unified_alerting]
ha_peers = "grafana-gossip:9094"
ha_listen_address = $__env{POD_IP}:9094

[unified_alerting.screenshots]
capture = true
upload_external_image_storage = false

[database]
type = "mysql"
host = <grafana-database>
user = <username>
password = <password>
name = "grafana"

[security]
allow_embedding = true
cookie_samesite = none
cookie_secure = true
```

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: 3.11.1
- Grafana version: 11.5.3
- Installed plugin or remote renderer service: Installed renderer plugin
- OS Grafana Image Renderer is installed on: Fedora CoreOS 38.20230806.3.0
- User OS & Browser: Windows 10 / MS Edge
- Others:
